blog/blog/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),

]

blog/main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    path("", TemplateView.as_view(template_name="main/index.html"), name="home_page"),
    path("posts/", views.PostListView.as_view(), name="posts"),
    path("posts/create/", views.post_create, name="post_create"),
    path("post/<int:post_id>/", views.post_show, name="post_show"),
    path("post/update/<int:post_id>/", views.post_update, name="post_update"),

    path("authors/new/", views.authors_new, name="authors_new"),
    path("authors/all/", views.authors_all, name="authors_all"),
    path("authors/subscribe/", views.authors_sub, name="authors_sub"),
    path("authors/delete/all/", views.authors_del_all, name="authors_del_all"),

    path("books/all/", views.books_all, name="books_all"),

    path("categories/all/", views.categories_all, name="categories_all"),

    path("subscribers/all/", views.subscribers_all, name="subscribers_all"),

    path("api/posts/", views.api_posts, name="api_posts"),
    path("api/post/<int:post_id>/", views.api_post_show, name="api_post_show"),
    path("api/subscribe/", views.api_author_subscribe, name="api_subscribe"),
    path("api/subscribers/all/", views.api_subscribers_all, name="api_subscribers_all"),
    path("api/authors/all/", views.api_authors_all, name="api_authors_all"),
    path("api/authors/new/", views.api_authors_new, name="api_authors_new"),

    path("about/", TemplateView.as_view(template_name="main/about.html"), name="about"),

    path("contact-us/create", views.CreateContactUsView.as_view(), name="contact_us_create"),
    path("contact-us/all", views.ContactUsListView.as_view(), name="contact_us_all"),
]

blog/main/models.py
from django.db import models
from django.utils.timezone import now


class Author(models.Model):
    name = models.CharField("Author's Name", max_length=100)
    email = models.EmailField("Author's Email", max_length=100)

    def __str__(self):
        return self.name


class Subscriber(models.Model):
    class Meta:
        unique_together = ["email_to", "author_id"]
    email_to = models.EmailField("Subscriber's Email", max_length=100)
    author_id = models.ForeignKey("Author", on_delete=models.CASCADE)

    def __str__(self):
        return self.email_to


class Post(models.Model):
    title = models.CharField("Title", max_length=100)
    description = models.CharField("Description", max_length=100)
    content = models.TextField("Text")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(default=now)

    def __str__(self):
        return self.title


class Comments(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField("Comment")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return self.post


class Logger(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    time_execution = models.FloatField("time_exec")
    path = models.CharField("path", max_length=100)
    utm = models.CharField("utm", max_length=100)
    ip = models.GenericIPAddressField()

    def __str__(self):
        return self.created


class Book(models.Model):
    title = models.CharField("Book title", max_length=250)
    author = models.ForeignKey("Author", on_delete=models.CASCADE, related_name="books")
    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name="books")

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField("Category", max_length=250)

    def __str__(self):
        return self.title


class ContactUs(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

blog/main/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from .authors_services import authors, delete_all_authors, new_author
from .books_services import books
from .categories_services import categories
from .form import CommentForm, ContactUsForm, PostForm, SubscribeForm
from .models import Author, ContactUs, Post
from .post_services import post_all, post_find
from .subsribers_services import sub_all
# from .tasks import send_email


# def posts(request):
#     return render(request, "main/posts.html", {"title": "Posts", "posts": post_all()})


def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts")
    else:
        form = PostForm()
    context = {
        "form": form,
    }
    return render(request, "main/post_create.html", context=context)


def post_show(request, post_id):
    post = post_find(post_id)
    comments = post.comments.all()

    new_comment = None

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect(request.META.get("HTTP_REFERER"))
    else:
        form = CommentForm()
    context = {
        "form": form,
        "post": post,
        "comments": comments,
        "new_comment": new_comment,
    }
    return render(request, "main/post_show.html", context=context)


def post_update(request, post_id):
    pst = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = PostForm(instance=pst, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts")
    else:
        form = PostForm(instance=pst)
    context = {
        "form": form,
    }
    return render(request, "main/post_update.html", context=context)


def authors_new(request):
    new_author()
    return redirect("authors_all")


def authors_all(request):
    all_authors = authors().prefetch_related("books")
    return render(request, "main/authors.html", {"title": "Authors", "authors": all_authors})


def authors_sub(request):
    subscribe_success = False
    # email_to = request.POST.get("email_to")
    # author_id = request.POST.get("author_id")

    if request.method == "POST":
        form = SubscribeForm(request.POST)
        if form.is_valid():
            form.save()
            subscribe_success = True
    else:
        form = SubscribeForm()

    if subscribe_success:
        # author = Author.objects.get(id=author_id)
        # send_email(email_to, author.name)
        return redirect("subscribers_all")

    context = {
        "form": form,
    }
    return render(request, "main/authors_subscribe.html", context=context)


def authors_del_all(request):
    delete_all_authors()
    return redirect("authors_all")


def books_all(request):
    all_books = books().only("id", "title", "author__name", "category__title").select_related("author", "category")
    return render(request, "main/books.html", {"title": "Books", "books": all_books})


def categories_all(request):
    all_categories = categories().prefetch_related("books")
    return render(request, "main/categories.html", {"title": "Categories", "categories": all_categories})


def subscribers_all(request):
    return render(request, "main/subscribers.html", {"title": "Subscribers", "subscribers": sub_all()})


def api_posts(request):
    all_posts = post_all()
    posts_list = list(all_posts.values())
    return JsonResponse(posts_list, safe=False)


def api_post_show(request, post_id):
    post = post_find(post_id)
    data = {
        "post_title": post.title,
        "post_description": post.description,
        "post_content": post.content
    }
    return JsonResponse(data, safe=False)


def api_author_subscribe(request):
    author_id = request.GET.get("author_id")
    email_to = request.GET.get("email_to")
    data = {"author_id": author_id, "email_to": email_to}
    return JsonResponse(data, safe=False)


def api_subscribers_all(request):
    all_subs = sub_all()
    subs_list = list(all_subs.values())
    return JsonResponse(subs_list, safe=False)


def api_authors_all(request):
    all_authors = authors()
    authors_list = list(all_authors.values())
    return JsonResponse(authors_list, safe=False)


def api_authors_new(request):
    new_author()
    author = Author.objects.last()
    data = {
        "author_id": author.id,
        "author_name": author.name,
        "author_email": author.email
    }
    return JsonResponse(data, safe=False)


class PostListView(ListView):
    queryset = post_all()
    template_name = "main/posts.html"


class CreateContactUsView(CreateView):
    success_url = reverse_lazy("home_page")
    model = ContactUs
    form_class = ContactUsForm


class ContactUsListView(ListView):
    queryset = ContactUs.objects.all()
    template_name = "main/contact_us_all.html"

blog/main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<div class="content">
    <h1>{{ title }}</h1>
    <br>
    <div class="payload">
        <p align="center" style="font-size:30px">
            First Django project, about
        </p>
    </div>

</div>

{% endblock %}

blog/main/templates/main/authors.html
{% extends 'main/base.html' %}

{% block title %}Authors{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <div class="payload">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Author ID</th>
                <th scope="col">Author Name</th>
                <th scope="col">Author Email</th>
                <th scope="col">Count of Books</th>
            </tr>
            </thead>
            <tbody>
            {% for author in authors %}
            <tr>
                <th scope="row">{{ author.id }}</th>
                <td>{{ author.name }}</td>
                <td>{{ author.email }}</td>
                <td>{{ author.books.count }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

blog/main/templates/main/authors_subscribe.html
{% extends 'main/base.html' %}

{% block title %}Subscribe to Author{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <div class="error">
        {{ form.errors }}
    </div>
    <div class="payload">
        <form method="POST">
            {% csrf_token %}

            {{ form.email_to }}
            <br><br>
            {{ form.author_id }}
            <br>
            <br>
            <button class="btn btn-outline-warning">Subscribe</button>
        </form>
    </div>
</div>
{% endblock %}

blog/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Blog{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'assets/images/favicon' %}/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'assets/images/favicon' %}/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'assets/images/favicon' %}/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/images/favicon' %}/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'assets/images/favicon' %}/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'assets/images/favicon' %}/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'assets/images/favicon' %}/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'assets/images/favicon' %}/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/favicon' %}/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'assets/images/favicon' %}/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/favicon' %}/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/images/favicon' %}/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicon' %}/favicon-16x16.png">
    <link rel="manifest" href="{% static 'assets/images/favicon' %}/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'assets/images/favicon' %}/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home_page' %}">Home page</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'post_create' %}"> Create Post </a>
            <a class="nav-item nav-link" href="{% url 'posts' %}"> Posts </a>
            <a class="nav-item nav-link" href="{% url 'authors_new' %}"> Create New Author </a>
            <a class="nav-item nav-link" href="{% url 'authors_all' %}"> Authors </a>
            <a class="nav-item nav-link" href="{% url 'books_all' %}"> Books </a>
            <a class="nav-item nav-link" href="{% url 'categories_all' %}"> Categories </a>
            <a class="nav-item nav-link" href="{% url 'authors_sub' %}"> Subscribe to Author </a>
            <a class="nav-item nav-link" href="{% url 'subscribers_all' %}"> All Subscribers </a>
            <a class="nav-item nav-link" href="{% url 'contact_us_create' %}"> Contact Us </a>
            <a class="nav-item nav-link" href="{% url 'contact_us_all' %}"> Contact Us Messages </a>
            <a class="nav-item nav-link" href="{% url 'about' %}"> About </a>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}
<br>
<footer class="bg-light text-center text-lg-start">
    <div class="text-center p-3">
        <span class="text-muted"> © 2021 Copyright: DEDMOPOZ </span>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

blog/main/templates/main/books.html
{% extends 'main/base.html' %}

{% block title %}Books{% endblock %}
{% block content %}

<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <div class="payload">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Book ID</th>
                <th scope="col">Book Title</th>
                <th scope="col">Author Name</th>
                <th scope="col">Category</th>
            </tr>
            </thead>
            <tbody>
            {% for book in books %}
            <tr>
                <th scope="row">{{ book.id }}</th>
                <td>{{ book.title }}</td>
                <td>{{ book.author.name }}</td>
                <td>{{ book.category.title }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

blog/main/templates/main/categories.html
{% extends 'main/base.html' %}

{% block title %}Categories{% endblock %}
{% block content %}

<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <div class="payload">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Category ID</th>
                <th scope="col">Category Title</th>
                <th scope="col">Number of Books</th>
            </tr>
            </thead>
            <tbody>
            {% for category in categories %}
            <tr>
                <th scope="row">{{ category.id }}</th>
                <td>{{ category.title }}</td>
                <td>{{ category.books.count }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

blog/main/templates/main/contact_us_all.html
{% extends 'main/base.html' %}

{% block title %}Messages{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <div class="payload">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Email</th>
                <th scope="col">Subject</th>
                <th scope="col">Message</th>
            </tr>
            </thead>
            <tbody>
                {% for contact in contactus_list %}
                <tr>
                    <th scope="row">{{ contact.email }}</a></th>
                    <td>{{ contact.subject }}</td>
                    <td>{{ contact.message }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

blog/main/templates/main/contactus_form.html
{% extends 'main/base.html' %}

{% block title %}Contact Us{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <div class="payload">
        <form action="{% url 'contact_us_create' %}" method="POST">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="btn btn-outline-warning">Send</button>
        </form>
    </div>
</div>
{% endblock %}

blog/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
<div class="content">
    <h1>{{ title }}</h1>
    <br>
    <div class="payload">
        <p align="center" style="font-size:30px">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam aut consectetur, cumque error incidunt laborum laudantium obcaecati porro vero vitae! Aperiam consequatur magnam magni nisi possimus quaerat, quisquam sequi tenetur.
        </p>
    </div>
</div>

{% endblock %}

blog/main/templates/main/post_create.html
{% extends 'main/base.html' %}

{% block title %}Create Post{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <div class="error">
        {{ form.errors }}
    </div>
    <div class="payload">
        <form method="POST">
            {% csrf_token %}
            {{ form.title }}
            {{ form.description }}
            {{ form.content }}
            <button class="btn btn-outline-warning">Create Post</button>
        </form>
    </div>
</div>
{% endblock %}

blog/main/templates/main/post_show.html
{% extends 'main/base.html' %}

{% block title %}Post{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <div class="error">
        {{ form.errors }}
    </div>
    <div class="card border-dark mb-3">
    <div class="card-header">{{ post.title }}</div>
    <div class="card-body">
        <h5 class="card-title">{{ post.description }}</h5>
        <p class="card-text">{{ post.content }}</p>
    <button class="btn btn-outline-warning">
            <a href="{% url 'post_update' post_id=post.id %}"> Edit Post</a>
    </button>
    </div>
    <div class="card-footer">
        <form method="POST">
            {% csrf_token %}
            {{ form.comment }}
            <button class="btn btn-outline-warning">
                <a>Comment</a>
            </button>
        </form>
    </div>
    <div class="card-footer">
        {% for comment in comments %}
            <div class="comment">
                {{ comment.comment }}
            </div>
        {% empty %}
            <p>There are no comments yet.</p>
        {% endfor %}
    </div>
    </div>
</div>
{% endblock %}

blog/main/templates/main/post_update.html
{% extends 'main/base.html' %}

{% block title %}Update Post{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <div class="error">
        {{ form.errors }}
    </div>
    <div class="payload">
        <form method="POST">
            {% csrf_token %}
            {{ form.title }}
            {{ form.description }}
            {{ form.content }}
            <button class="btn btn-outline-warning">Update Post</button>
        </form>
    </div>
</div>
{% endblock %}

blog/main/templates/main/posts.html
{% extends 'main/base.html' %}

{% block title %}Posts{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <br>
    {% if post_list %}
    <div class="payload">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Post Title</th>
                <th scope="col">Post Description</th>
            </tr>
            </thead>
            <tbody>
                {% for post in post_list %}
                <tr>
                    <th scope="row"><a href="{% url 'post_show' post_id=post.id %}">{{ post.title }}</a></th>
                    <td>{{ post.description }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <h4> Nothing to display </h4>
    {% endif %}
</div>
{% endblock %}

blog/main/templates/main/subscribers.html
{% extends 'main/base.html' %}

{% block title %}Subscribers{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <div class="payload">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Subscriber ID</th>
                <th scope="col">Subscriber's Email</th>
                <th scope="col">Author</th>
            </tr>
            </thead>
            <tbody>
            {% for subscriber in subscribers %}
            <tr>
                <th scope="row">{{ subscriber.id }}</th>
                <td>{{ subscriber.email_to }}</td>
                <td>{{ subscriber.author_id }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}